language: csharp
solution: RuleEngine.sln
script:
  - xbuild /p:Configuration=Release RuleEngine.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./RuleEngine.Tests/bin/Release/RuleEngine.Tests.dll
after_success:
  - bash <(curl -s https://codecov.io/bash)